#!/usr/bin/env bash
# =============================================================================
# ci-check.sh — Companion script for CI/CD and Automation
#
# Checks for common CI configuration files, validates pipeline setup, and
# generates quality gate pipeline templates.
#
# Usage:
#   bash ./scripts/ci-check.sh check
#     Scan the project for CI configuration and report status.
#
#   bash ./scripts/ci-check.sh template <type>
#     Generate a CI pipeline template. Types: gh-actions, gitlab-ci.
#     Example: bash ./scripts/ci-check.sh template gh-actions
#
#   bash ./scripts/ci-check.sh gates
#     Output the quality gate pipeline checklist.
# =============================================================================

set -euo pipefail

MODE="${1:-check}"

case "$MODE" in
  check)
    echo "=== CI/CD Configuration Check ==="
    echo ""
    
    TOOLS=0
    
    # GitHub Actions
    if ls .github/workflows/*.yml 2>/dev/null | head -1 >/dev/null; then
      echo "  ✓ GitHub Actions: $(ls .github/workflows/*.yml | wc -l) workflow(s)"
      TOOLS=$((TOOLS + 1))
    fi
    
    # GitLab CI
    if [ -f ".gitlab-ci.yml" ]; then
      echo "  ✓ GitLab CI: .gitlab-ci.yml found"
      TOOLS=$((TOOLS + 1))
    fi
    
    # CircleCI
    if [ -f ".circleci/config.yml" ]; then
      echo "  ✓ CircleCI: .circleci/config.yml found"
      TOOLS=$((TOOLS + 1))
    fi
    
    # Jenkins
    if ls Jenkinsfile* 2>/dev/null | head -1 >/dev/null; then
      echo "  ✓ Jenkins: $(ls Jenkinsfile* | head -1) found"
      TOOLS=$((TOOLS + 1))
    fi
    
    # Pre-commit hooks
    if [ -f ".pre-commit-config.yaml" ]; then
      echo "  ✓ Pre-commit: hooks configured"
      TOOLS=$((TOOLS + 1))
    fi
    
    # Makefile
    if [ -f "Makefile" ]; then
      echo "  ✓ Makefile: build automation present"
    fi
    
    # Docker
    if [ -f "Dockerfile" ]; then
      echo "  ✓ Dockerfile: container build configured"
    fi
    
    if [ "$TOOLS" -eq 0 ]; then
      echo "  ✗ No CI/CD configuration detected."
      echo "  Consider: bash ./scripts/ci-check.sh template gh-actions"
    else
      echo ""
      echo "  $TOOLS CI tool(s) detected."
    fi
    echo ""
    
    # Check for key quality gates
    echo "--- Quality Gates ---"
    GATES=0
    [ -f "package.json" ] && GATES=$((GATES + 1)) && echo "  ✓ package.json (build target)"
    [ -f ".eslintrc*" ] || [ -f "eslint.config.*" ] && GATES=$((GATES + 1)) && echo "  ✓ Linter config found"
    [ -f "tsconfig.json" ] && GATES=$((GATES + 1)) && echo "  ✓ TypeScript config found"
    [ -f "vitest.config.*" ] || [ -f "jest.config.*" ] || [ -f ".mocharc*" ] && GATES=$((GATES + 1)) && echo "  ✓ Test runner config found"
    [ -f "Dockerfile" ] && GATES=$((GATES + 1)) && echo "  ✓ Docker build configured"
    echo "  $GATES quality gate(s) configurable from detected files."
    ;;

  template)
    TYPE="${2:-gh-actions}"
    
    case "$TYPE" in
      gh-actions)
        cat << "YAML"
# .github/workflows/ci.yml — Generated by ci-check.sh
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality-gates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run typecheck || npx tsc --noEmit

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

  # Add more jobs here: integration tests, e2e, deploy
YAML
        ;;
      gitlab-ci)
        cat << "YAML"
# .gitlab-ci.yml — Generated by ci-check.sh
stages:
  - lint
  - test
  - build

lint:
  stage: lint
  script:
    - npm ci
    - npm run lint
    - npx tsc --noEmit

test:
  stage: test
  script:
    - npm ci
    - npm test

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/
YAML
        ;;
      *)
        echo "Unknown template type: $TYPE" >&2
        echo "Supported: gh-actions, gitlab-ci" >&2
        exit 1
        ;;
    esac
    ;;

  gates)
    cat << "GATES"
=== Quality Gate Pipeline Checklist ===

## Pre-Merge Gates (required for every change)
- [ ] Lint check (eslint, prettier, ruff)
- [ ] Type check (tsc --noEmit, mypy, pyright)
- [ ] Unit tests (jest, vitest, pytest)
- [ ] Build (npm run build, go build, cargo build)
- [ ] No secrets in diff

## Post-Merge Gates (optional, recommended)
- [ ] Integration tests
- [ ] E2E tests
- [ ] Performance regression check
- [ ] Security scan (npm audit, pip-audit)
- [ ] Deploy to staging
- [ ] Smoke tests on staging
- [ ] Deploy to production

## CI Best Practices
- [ ] Fail fast: lint before test, test before build
- [ ] Cache dependencies between runs
- [ ] Parallelize independent jobs
- [ ] Set timeouts on all jobs
- [ ] Tag artifacts for traceability
- [ ] Notify on failure (Slack, email, etc.)
GATES
    ;;

  *)
    echo "Usage: $0 {check|template|gates}"
    echo ""
    echo "  check                    — Scan for CI configuration"
    echo "  template gh-actions      — Generate GitHub Actions workflow"
    echo "  template gitlab-ci       — Generate GitLab CI config"
    echo "  gates                    — Quality gate pipeline checklist"
    exit 1
    ;;
esac
